= Mask (Gangle's Song) (feat. Marissa Lenti)
:author: Sarah Rogue
:category: humour
:date: Sun, 17 May 2026 02:50:25 -0400
:description: Gangle's song from YouTube
:layout: post
:title: Mask (Gangle's Song) (feat. Marissa Lenti)

[source, text]
feel a little bit crazy lately
wanna set the whole world on fire
should i jump out of a window, maybe
no instead i'll just smile smile smile

[source, text]
what's inside
i gotta find
don't wanna hide
the real me

== but the world is fucking bleak

[source, text]
so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i block it out out out
i block it out

[source, text]
and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i block it out out out
i block it out

[source, text]
people tell me i have a problem
cause i wanna stay in all night
up and down i get low so often
need a new mask to take me high

[source, text]
what's inside
i gotta find
don't wanna hide
the real me 

== but the world is fucking bleak

[source, text]
so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i block it out out out
i block it out

[source, text]
and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i block it out out out
i block it out

== wanna take your mask away
[source, text]
no i like it
it's okay

== but you're crying everyday
[source, text]
i feel it in a silly way

== bi-bi-po-polarity
[source, text]
and it looks so good on me

== boy i'm so glad i asked
[source, text]
that is why i wear a ...

[source, text]
insecurity
it's a part of me
maybe that's okay

[source, text]
i want you to see
the hidden part of me
should i take my mask off

== NO!

[source, text]
so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i block it out out out
i block it out

[source, text]
and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i block it out out out
i block it out

[source, text]
feel a little bit crazy lately
